<a href="https://colab.research.google.com/github/Goyalg/colabnotebooks/blob/master/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
pip install matplotlib

In [0]:
pip install pandas

In [0]:
import numpy as np
data = np.random.randn(2,3)


In [0]:
data

array([[-0.64066481,  0.37581046,  2.69148503],
       [ 0.64269274, -0.7283079 , -0.42419466]])

In [0]:
data*100

array([[-64.06648102,  37.58104629, 269.1485034 ],
       [ 64.26927395, -72.83078989, -42.41946569]])

In [0]:
data + data

array([[-1.28132962,  0.75162093,  5.38297007],
       [ 1.28538548, -1.4566158 , -0.84838931]])

In [0]:
data - data

array([[0., 0., 0.],
       [0., 0., 0.]])

In [0]:
data1 = [6,7.5,11,22,43]
data2 = [[10,34,20.5,12],[10.2,15.6,11,46]]
arr1 = np.array(data1)
arr2 = np.array(data2)

In [0]:
arr1
arr2

array([list([10, 34, 20.5, 12]), list([10.2, 15.6, 11, 46, 13])],
      dtype=object)

In [0]:
arr1

array([ 6. ,  7.5, 11. , 22. , 43. ])

In [0]:
arr2

array([[10. , 34. , 20.5, 12. ],
       [10.2, 15.6, 11. , 46. ]])

In [0]:
arr3 = np.arange(10)

In [0]:
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
arr3.dtype

dtype('int64')

In [0]:
np.reshape()